# Generated by Django 5.1.4 on 2025-01-04 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_products_orderitem_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='Products',
        ),
    ]
